version: '3.8'

services:
  pokeapi-container:
    build: .
    container_name: pokeapi-container
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: sh -c "python -m uvicorn main:app --host 0.0.0.0 --port 8000"

  redis:
    image: redis:latest
    container_name: pokeapi-redis
    ports:
      - "6379:6379"
